services:
  db:
    image: postgres:16
    container_name: dentalcrm-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dentalcrm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -p 5432 -U postgres -d dentalcrm"]
      interval: 5s
      timeout: 5s
      retries: 20

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: dentalcrm-server
    environment:
      NODE_ENV: production
      PORT: 4000

      DATABASE_URL: postgresql://postgres:postgres@db:5432/dentalcrm?schema=public

      JWT_ACCESS_SECRET: 0a21d29f9407dd31a78d30f0a541c4142e9bfab02c9723c1d108344d04d3fced
      JWT_REFRESH_SECRET: de1112ada693fc6235f5d6aa8ab6d4f3098c5a5f8c593e9ed6c99db4c1cc0b3d0d0ca4f6b7b71bb006b15e44400b840cbf08c9196038f9923b2307183849d10e
      ACCESS_TOKEN_TTL: 4h
      REFRESH_TOKEN_TTL: 30d
      SEED_ON_STARTUP: ${SEED_ON_STARTUP:-true}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: dentalcrm-client
    environment:
      VITE_API_URL: /api
      VITE_PROXY_TARGET: http://server:4000
    depends_on:
      - server
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"

volumes:
  pgdata:
  client_node_modules:
